// Package catalog builds a read-only signal inventory for presentation and
// future MCP clients. It has no access to protocol controllers or live values.
package catalog

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"pbmt/internal/application/sclmodel"
	"pbmt/internal/config"
	"pbmt/internal/domain/goose"
	"pbmt/internal/domain/sv"
)

const FileName = "mcp_catalog.json"

type Catalog struct {
	SchemaVersion       int       `json:"schema_version"`
	GeneratedAt         time.Time `json:"generated_at"`
	Revision            string    `json:"revision"`
	ConfigurationDigest string    `json:"configuration_digest"`
	Project             string    `json:"project"`
	Mode                string    `json:"mode"`
	Status              string    `json:"status"`
	ConfigurationState  string    `json:"configuration_state"`
	Notes               []string  `json:"notes"`
	Modules             []Module  `json:"modules"`
}

type Module struct {
	ID                string   `json:"id"`
	Direction         string   `json:"direction"`
	ConfiguredEnabled bool     `json:"configured_enabled"`
	Interface         string   `json:"interface"`
	Streams           []Stream `json:"streams"`
}

type Stream struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Source       string         `json:"source"`
	SchemaStatus string         `json:"schema_status"`
	Notes        []string       `json:"notes,omitempty"`
	Metadata     map[string]any `json:"metadata,omitempty"`
	Signals      []Signal       `json:"signals"`
}

type Signal struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	Type         string   `json:"type"`
	Reference    string   `json:"reference,omitempty"`
	EntryIndex   *int     `json:"entry_index,omitempty"`
	ChannelIndex *int     `json:"channel_index,omitempty"`
	Unit         string   `json:"unit,omitempty"`
	Basis        string   `json:"basis,omitempty"`
	BitLength    int      `json:"bit_length,omitempty"`
	Count        *int     `json:"count,omitempty"`
	ByteLength   int      `json:"byte_length,omitempty"`
	MaxLength    int      `json:"max_length,omitempty"`
	LengthUnit   string   `json:"length_unit,omitempty"`
	IsTemplate   bool     `json:"is_template,omitempty"`
	Encoding     string   `json:"encoding,omitempty"`
	Children     []Signal `json:"children,omitempty"`
	Fields       []Field  `json:"fields,omitempty"`
}

type Field struct {
	Name      string `json:"name"`
	Type      string `json:"type"`
	Unit      string `json:"unit,omitempty"`
	Meaning   string `json:"meaning,omitempty"`
	Encoding  string `json:"encoding,omitempty"`
	BitLength int    `json:"bit_length,omitempty"`
}

// Generate describes the supplied configuration and re-reads the project ICD.
// Refresh is the disk-backed entry point; no function applies runtime settings.
func Generate(root string, cfg *config.Config) (*Catalog, error) {
	if cfg == nil || root == "" {
		return nil, fmt.Errorf("open a project before generating the catalog")
	}
	descriptions, message := sclmodel.ProjectGooseDescriptions(root)
	c := &Catalog{SchemaVersion: 2, Project: filepath.Base(filepath.Clean(root)), Mode: "description_only", Status: "complete", ConfigurationState: "not_compared", Notes: []string{
		"Generated from project configuration and ICD. Do not edit this file; refresh regenerates it.",
		"Directions are relative to PBMT: input = received, output = transmitted.",
		"No live values, commands or runtime availability are included. An enabled module is not necessarily running.",
		"GOOSE input names are expected descriptions; a received frame must pass ICD identity, revision and structure checks before labels are used.",
		"Signal IDs belong to this catalog revision; clients must re-resolve them after configuration or ICD changes.",
		"Entry and channel indices are zero-based. is_template marks schemas, not addressable array elements.",
		"Encoding fields describe existing PBMT representations, not the contract of future MCP commands.",
		message,
	}, Modules: []Module{
		{ID: "goose_sub", Direction: "input", ConfiguredEnabled: cfg.GooseSub.Enabled, Interface: cfg.GooseSub.Interface, Streams: []Stream{}},
		{ID: "goose_pub", Direction: "output", ConfiguredEnabled: cfg.GoosePub.Enabled, Interface: cfg.GoosePub.Interface, Streams: []Stream{}},
		{ID: "sv_sub", Direction: "input", ConfiguredEnabled: cfg.SVSub.Enabled, Interface: cfg.SVSub.Interface, Streams: []Stream{}},
		{ID: "sv_pub", Direction: "output", ConfiguredEnabled: cfg.SVPub.Enabled, Interface: cfg.SVPub.Interface, Streams: []Stream{}},
	}}
	for _, sub := range cfg.GooseSub.Subscriptions {
		st := newStream("goose_sub", sub.Name, "cfg/goose_sub.yaml")
		st.Metadata = map[string]any{"gocb_ref": sub.GocbRef, "dat_set": sub.DatSet, "app_id": uint16(sub.AppID), "dst_mac": sub.DstMAC, "go_id": sub.GoID, "conf_rev": sub.ConfRev}
		g, reason := sclmodel.GooseDescription(sub, descriptions)
		if g == nil {
			st.SchemaStatus = "unresolved"
			st.Notes = []string{reason, "Entry count and types are unknown until a frame is received; no placeholder signals are invented."}
		} else {
			st.Source += " + project_icd"
			st.Metadata["expected_conf_rev"] = g.ConfRev
			for i, t := range g.Entries {
				v := gooseSignal(t, fmt.Sprintf("%s/entry/%d", st.ID, i))
				v.Reference = t.Name
				if _, name, ok := strings.Cut(t.Name, "/"); ok {
					v.Name = name
				}
				v.EntryIndex = intPtr(i)
				st.Signals = append(st.Signals, v)
			}
		}
		c.Modules[0].Streams = append(c.Modules[0].Streams, st)
	}
	for _, pub := range cfg.GoosePub.Publishers {
		st := newStream("goose_pub", pub.Name, "cfg/goose_pub.yaml")
		st.Metadata = map[string]any{"gocb_ref": pub.GocbRef, "dat_set": pub.DatSet, "app_id": uint16(pub.AppID), "dst_mac": pub.DstMAC, "conf_rev": pub.ConfRev}
		for i, e := range pub.Dataset {
			kind := map[string]string{"bool": "BOOLEAN", "quality": "Quality", "int": "INTEGER", "uint": "UNSIGNED", "float": "FLOAT", "string": "VISIBLE_STRING", "utc_time": "UTC_TIME"}[e.Type]
			if kind == "" {
				kind = "UNKNOWN"
				st.SchemaStatus = "unresolved"
				st.Notes = append(st.Notes, fmt.Sprintf("Entry %d has unsupported configured type %q.", i, e.Type))
			}
			name := e.Name
			if name == "" {
				name = fmt.Sprintf("Entry%d", i+1)
			}
			v := Signal{ID: fmt.Sprintf("%s/entry/%d", st.ID, i), Name: name, Type: kind, EntryIndex: intPtr(i)}
			if kind == "Quality" {
				v.BitLength = goose.QualityBitLength
				v.Encoding = "uint32_quality_mask_to_msb_first_bit_string"
			}
			st.Signals = append(st.Signals, v)
		}
		c.Modules[1].Streams = append(c.Modules[1].Streams, st)
	}
	for _, sub := range cfg.SVSub.Subscriptions {
		st := newStream("sv_sub", sub.Name, "cfg/sv_sub.yaml + fixed_9_2le_channels")
		st.Metadata = map[string]any{"sv_id": sub.SvID, "app_id": uint16(sub.AppID), "dst_mac": sub.DstMAC, "base_vector": sub.BaseVector, "current_display_coefficient": sub.CurrentCoefficient, "voltage_display_coefficient": sub.VoltageCoefficient}
		st.Notes = []string{"A/V refer to wire-scaled values. KI/KU are display multipliers; primary/secondary attribution is not inferred."}
		st.Signals = svSignals(st.ID, false)
		c.Modules[2].Streams = append(c.Modules[2].Streams, st)
	}
	for _, pub := range cfg.SVPub.Streams {
		st := newStream("sv_pub", pub.Name, "cfg/sv_pub.yaml + fixed_9_2le_channels")
		st.Metadata = map[string]any{"sv_id": pub.SvID, "app_id": uint16(pub.AppID), "dst_mac": pub.DstMAC, "conf_rev": pub.ConfRev}
		st.Signals = svSignals(st.ID, true)
		c.Modules[3].Streams = append(c.Modules[3].Streams, st)
	}
	// Disabled configurations can contain duplicate names. Reject ambiguity
	// rather than emit colliding IDs that a future client could misaddress.
	seen := map[string]bool{}
	for _, m := range c.Modules {
		for _, s := range m.Streams {
			if s.SchemaStatus != "described" {
				c.Status = "partial"
			}
			if s.Name == "" || seen[s.ID] {
				return nil, fmt.Errorf("%s: missing or duplicate stream name %q", m.ID, s.Name)
			}
			seen[s.ID] = true
		}
	}
	// Bind revisions to all GOOSE/SV settings, without exporting PTP settings.
	digest, err := configurationDigest(cfg)
	if err != nil {
		return nil, err
	}
	c.ConfigurationDigest = digest
	return c, c.finalize()
}

func configurationDigest(cfg *config.Config) (string, error) {
	if cfg == nil {
		return "", nil
	}
	raw, err := json.Marshal([]any{cfg.GooseSub, cfg.GoosePub, cfg.SVSub, cfg.SVPub})
	if err != nil {
		return "", err
	}
	hash := sha256.Sum256(raw)
	return hex.EncodeToString(hash[:]), nil
}

func (c *Catalog) finalize() error {
	c.Revision = ""
	c.GeneratedAt = time.Time{}
	raw, err := json.Marshal(c)
	if err != nil {
		return err
	}
	hash := sha256.Sum256(raw)
	c.Revision = hex.EncodeToString(hash[:])
	c.GeneratedAt = time.Now().UTC()
	return nil
}

func newStream(module, name, source string) Stream {
	return Stream{ID: module + "/" + url.PathEscape(name), Name: name, Source: source, SchemaStatus: "described", Signals: []Signal{}}
}

func intPtr(v int) *int { return &v }

func gooseSignal(t *sclmodel.Type, id string) Signal {
	s := Signal{ID: id, Name: t.Name, Type: t.Kind}
	size := t.Size
	if size < 0 {
		size = -size
	}
	switch t.Kind {
	case "ARRAY":
		s.Count = intPtr(size)
	case "INTEGER", "UNSIGNED", "FLOAT", "BIT_STRING":
		s.BitLength = size
	case "VISIBLE_STRING":
		s.MaxLength = size
		s.LengthUnit = "characters"
	case "MMS_STRING":
		s.MaxLength = size
		s.LengthUnit = "octets"
	case "OCTET_STRING":
		s.MaxLength = size
		s.LengthUnit = "octets"
	case "BINARY_TIME":
		s.ByteLength = size
	}
	if t.Kind == "BIT_STRING" {
		s.Encoding = "msb_first_bit_string_payload"
	}
	if t.Kind == "BIT_STRING" && (size == 13 || size == 14) && (t.Name == "q" || strings.HasSuffix(t.Name, ".q")) {
		s.Type = "Quality"
	}
	// Retain array element schemas without expanding thousands of identical
	// elements. Every descendant of the element schema is marked as a template.
	for i, ch := range t.Children {
		childID := fmt.Sprintf("%s/field/%d", id, i)
		if t.Kind == "ARRAY" {
			childID = id + "/element_schema"
		}
		v := gooseSignal(ch, childID)
		if t.Kind == "ARRAY" {
			v.Name = "element schema"
			markTemplate(&v)
		}
		s.Children = append(s.Children, v)
	}
	return s
}

func markTemplate(s *Signal) {
	s.IsTemplate = true
	for i := range s.Children {
		markTemplate(&s.Children[i])
	}
}

func svSignals(id string, output bool) []Signal {
	var signals []Signal
	for i, name := range sv.ChannelNames {
		unit := "A"
		if i >= sv.ChUa {
			unit = "V"
		}
		basis := "wire_scaled; primary_or_secondary_unspecified"
		fields := []Field{{Name: "rms", Type: "number", Unit: unit}, {Name: "phase", Type: "number", Unit: "deg", Meaning: "relative to the configured base vector"}, {Name: "frequency", Type: "number", Unit: "Hz"}, {Name: "quality", Type: "SV Quality"}, {Name: "instantaneous", Type: "number", Unit: unit}}
		fields[0].Meaning = "root mean square, not peak amplitude"
		fields[3].Encoding = "uint32_quality_bitmask"
		fields[3].BitLength = 32
		if output {
			basis = "secondary"
			fields = fields[:4]
			fields[1].Meaning = "electrical phase of the generated waveform"
		}
		signals = append(signals, Signal{ID: id + "/channel/" + name, Name: name, Type: "analog_channel", ChannelIndex: intPtr(i), Unit: unit, Basis: basis, Fields: fields})
	}
	return signals
}

// Save atomically replaces the derived file, never the source configuration.
func Save(root string, c *Catalog) error {
	if c == nil {
		return fmt.Errorf("catalog is unavailable")
	}
	raw, err := json.MarshalIndent(c, "", "  ")
	if err != nil {
		return err
	}
	f, err := os.CreateTemp(root, ".mcp-catalog-*")
	if err != nil {
		return err
	}
	defer os.Remove(f.Name())
	if _, err = f.Write(append(raw, '\n')); err != nil {
		f.Close()
		return err
	}
	if err = f.Sync(); err != nil {
		f.Close()
		return err
	}
	if err = f.Close(); err != nil {
		return err
	}
	return os.Rename(f.Name(), filepath.Join(root, FileName))
}
